from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import uvicorn
import os

app = FastAPI(title="HirePrep AI", description="Backend for HirePrep AI Interview Platform")

# Serve React App
# Mounts the 'dist' folder generated by 'npm run build'
if os.path.exists("dist"):
    app.mount("/", StaticFiles(directory="dist", html=True), name="static")

@app.get("/api/health")
async def health_check():
    return {"status": "healthy", "service": "HirePrep AI"}

# Catch-all route for SPA client-side routing
@app.exception_handler(404)
async def custom_404_handler(_, __):
    if os.path.exists("dist/index.html"):
        return FileResponse("dist/index.html")
    return {"error": "Frontend not built. Run 'npm run build' first."}

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
